export const FontAsset = {
  MontserratAlternateBold: require("./MontserratAlternates-Bold.ttf"),
  MontserratAlternateLight: require("./MontserratAlternates-Light.ttf"),
  MontserratAlternateMedium: require("./MontserratAlternates-Medium.ttf"),
  MontserratAlternateRegular: require("./MontserratAlternates-Regular.ttf"),
  MontserratAlternateSemiBold: require("./MontserratAlternates-SemiBold.ttf"),

  MontserratBold: require("./Montserrat-Bold.ttf"),
  MontserratLight: require("./Montserrat-Light.ttf"),
  MontserratMedium: require("./Montserrat-Medium.ttf"),
  MontserratRegular: require("./Montserrat-Regular.ttf"),
  MontserratSemiBold: require("./Montserrat-SemiBold.ttf"),

  SourGummyBold: require("./SourGummy-Bold.ttf"),
  SourGummyLight: require("./SourGummy-Light.ttf"),
  SourGummyMedium: require("./SourGummy-Medium.ttf"),
  SourGummyRegular: require("./SourGummy-Regular.ttf"),
  SourGummySemiBold: require("./SourGummy-SemiBold.ttf"),

  PoppinsBold: require("./Poppins-Bold.ttf"),
  PoppinsLight: require("./Poppins-Light.ttf"),
  PoppinsMedium: require("./Poppins-Medium.ttf"),
  PoppinsRegular: require("./Poppins-Regular.ttf"),
  PoppinsSemiBold: require("./Poppins-SemiBold.ttf"),

  TangerineRegular: require("./Tangerine-Regular.ttf"),
  TangerineBold: require("./Tangerine-Bold.ttf"),

  RobotoBold: require("./Roboto-Bold.ttf"),
  RobotoLight: require("./Roboto-Light.ttf"),
  RobotoMedium: require("./Roboto-Medium.ttf"),
  RobotoRegular: require("./Roboto-Regular.ttf"),
  RobotoSemiBold: require("./Roboto-SemiBold.ttf"),

  CaveatBold: require("./Caveat-Bold.ttf"),
  CaveatLight: require("./Caveat-Regular.ttf"),
  CaveatMedium: require("./Caveat-Medium.ttf"),
  CaveatRegular: require("./Caveat-Regular.ttf"),
  CaveatSemiBold: require("./Caveat-SemiBold.ttf"),

  ChangaOneBold: require("./ChangaOne-Regular.ttf"),
  ChangaOneLight: require("./ChangaOne-Italic.ttf"),
  ChangaOneMedium: require("./ChangaOne-Italic.ttf"),
  ChangaOneRegular: require("./ChangaOne-Regular.ttf"),
  ChangaOneSemiBold: require("./ChangaOne-Regular.ttf"),

  DancingScriptBold: require("./DancingScript-Bold.ttf"),
  DancingScriptLight: require("./DancingScript-Regular.ttf"),
  DancingScriptMedium: require("./DancingScript-Medium.ttf"),
  DancingScriptRegular: require("./DancingScript-Regular.ttf"),
  DancingScriptSemiBold: require("./DancingScript-SemiBold.ttf"),

  LibreFranklinBold: require("./LibreFranklin-Bold.ttf"),
  LibreFranklinLight: require("./LibreFranklin-Light.ttf"),
  LibreFranklinMedium: require("./LibreFranklin-Medium.ttf"),
  LibreFranklinRegular: require("./LibreFranklin-Regular.ttf"),
  LibreFranklinSemiBold: require("./LibreFranklin-SemiBold.ttf"),

  NotoSansMonoBold: require("./NotoSansMono-Bold.ttf"),
  NotoSansMonoLight: require("./NotoSansMono-Light.ttf"),
  NotoSansMonoMedium: require("./NotoSansMono-Medium.ttf"),
  NotoSansMonoRegular: require("./NotoSansMono-Regular.ttf"),
  NotoSansMonoSemiBold: require("./NotoSansMono-SemiBold.ttf"),

  SpaceGroteskBold: require("./SpaceGrotesk-Bold.ttf"),
  SpaceGroteskLight: require("./SpaceGrotesk-Light.ttf"),
  SpaceGroteskMedium: require("./SpaceGrotesk-Medium.ttf"),
  SpaceGroteskRegular: require("./SpaceGrotesk-Regular.ttf"),
  SpaceGroteskSemiBold: require("./SpaceGrotesk-SemiBold.ttf"),
};

export const fontMap = {
  Montserrat: {
    light: "MontserratLight",
    regular: "MontserratRegular",
    medium: "MontserratMedium",
    semibold: "MontserratSemiBold",
    bold: "MontserratBold",
  },
  MontserratAlternate: {
    light: "MontserratAlternateLight",
    regular: "MontserratAlternateRegular",
    medium: "MontserratAlternateMedium",
    semibold: "MontserratAlternateSemiBold",
    bold: "MontserratAlternateBold",
  },
  SourGummy: {
    light: "SourGummyLight",
    regular: "SourGummyRegular",
    medium: "SourGummyMedium",
    semibold: "SourGummySemiBold",
    bold: "SourGummyBold",
  },
  Poppins: {
    light: "PoppinsLight",
    regular: "PoppinsRegular",
    medium: "PoppinsMedium",
    semibold: "PoppinsBold",
    bold: "PoppinsBold",
  },

  Roboto: {
    light: "RobotoLight",
    regular: "RobotoRegular",
    medium: "RobotoMedium",
    semibold: "RobotoSemiBold",
    bold: "RobotoBold",
  },
  Caveat: {
    light: "CaveatLight",
    regular: "CaveatRegular",
    medium: "CaveatMedium",
    semibold: "CaveatSemiBold",
    bold: "CaveatBold",
  },
  Tangerine: {
    light: "TangerineRegular",
    regular: "TangerineRegular",
    medium: "TangerineRegular",
    semibold: "TangerineBold",
    bold: "TangerineBold",
  },
  ChangaOne: {
    light: "ChangaOneLight",
    regular: "ChangaOneRegular",
    medium: "ChangaOneMedium",
    semibold: "ChangaOneSemiBold",
    bold: "ChangaOneBold",
  },
  DancingScript: {
    light: "DancingScriptLight",
    regular: "DancingScriptRegular",
    medium: "DancingScriptMedium",
    semibold: "DancingScriptSemiBold",
    bold: "DancingScriptBold",
  },
  LibreFranklin: {
    light: "LibreFranklinLight",
    regular: "LibreFranklinRegular",
    medium: "LibreFranklinMedium",
    semibold: "LibreFranklinSemiBold",
    bold: "LibreFranklinBold",
  },
  NotoSansMono: {
    light: "NotoSansMonoLight",
    regular: "NotoSansMonoRegular",
    medium: "NotoSansMonoMedium",
    semibold: "NotoSansMonoSemiBold",
    bold: "NotoSansMonoBold",
  },
  SpaceGrotesk: {
    light: "SpaceGroteskLight",
    regular: "SpaceGroteskRegular",
    medium: "SpaceGroteskMedium",
    semibold: "SpaceGroteskSemiBold",
    bold: "SpaceGroteskBold",
  },
} as const;

export type FontName = keyof typeof fontMap;
