export enum ROUTES {
  SPLASH = "Splash",
  LOGIN = "Login",
  REGISTER = "Register",
  TABS = "Main",
  TASKS = "Tasks",
  HISTORY = "History",
  NOTES = "Notes",
  PROFILE = "Profile",
  REELS = "Reels",
  CREATE_TASK = "CreateTask",
  CREATE_NOTE = "CreateNote",
  CREATE_VIDEO = "CreateVideo",
  VIEW_NOTE = "ViewNote",
  TASK_DETAIL = "TaskDetail",
  THEME = "Theme",
}
