export enum ROUTES {
  SPLASH = "Splash",
  LOGIN = "Login",
  REGISTER = "Register",
  TABS = "Main",
  TASKS = "Tasks",
  HISTORY = "History",
  NOTES = "Notes",
  PROFILE = "Profile",
  REELS = "Reels",
  CREATE_TASK = "CreateTask",
  CREATE_NOTE = "CreateNote",
  CREATE_VIDEO = "CreateVideo",
  RESET_PASSWORD = "ResetPassword",
  LISTS = "Lists",
  VIEW_NOTE = "ViewNote",
  VIEW_LIST = "ViewList",
  CREATE_LIST = "CreateList",
  TASK_DETAIL = "TaskDetail",
  THEME = "Theme",
  FONT = "Font",
  SINGLE_VIDEO = "SingleVideo",
  UPDATE_PROFILE = "UpdateProfile",
  ADD_EMAIL = "AddEmail",
  NOTIFICATION = "Notification",
  TEST_TOAST = "TestToast",
}
