// 🔹 Video payloads
export interface IVideoComment {
  _id?: string; // optional, generated by backend
  text: string;
  createdBy: string;
  createdAt?: string | Date;
  createdByDetails?: {
    name: string;
    image?: string;
  };
}

export interface IVideo {
  _id: string;
  title: string;
  url: string;
  createdBy: string;
  partnerWatched?: boolean;
  createdByDetails?: {
    name: string;
    image?: string;
  };
  createdAt: string;
  updatedAt: string;
  comments?: IVideoComment[]; // added comments array
}

export interface CreateVideoPayload {
  title: string;
  url: string; // URL or path of the uploaded video
  createdBy: string;
}

export interface UpdateVideoPayload {
  title?: string;
  url?: string; // updated field name consistent with IVideo
}

export interface AddVideoCommentPayload {
  createdBy: string;
  text: string;
}
